# VPS Default Configuration

# Visual Place Recognition (VPR) settings
vpr:
  method: "megaloc"  # Options: netvlad, megaloc
  top_k: 3  # Number of similar images to retrieve
  output_dir: "data/outputs/"
  ref_data_path: "data/ref"
  ref_descriptors_path: "data/outputs/ref.h5"
  query_descriptors_path: "data/outputs/query.h5"
  pairs_file_path: "data/outputs/pairs.txt"
  use_spatial_filtering: False   #是否开启空间过滤(上次定位结果附近，过滤远距离相似，暂时没必要开)
  spatial_radius: 1.0 #空间过滤半径
  similarity_threshold: 0.0001 #vpr相似度阈值 有点难确定
  history_file: "data/outputs/last_pose.txt" #上一次定位结果
  

# Pose Estimation settings
pose:
  method: "mast3r"  # Options: vggt, mast3r
  use_depth_pre: False #是否使用深度预估
  depth_pre_model_path: "checkpoints/moge2_model.pt" #深度预估模型路径
  vggt:
    model_path: "checkpoints/vggt_model.pt"  # If null, will download from HuggingFace
    image_size: 1024  # Input image size for VGGT
    ref_dir: "data/ref"
    results_dir: "data/outputs/poses"
  mast3r:
    model_path: "checkpoints/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth"
    image_size: 512  # Input image size for MASt3R
    batch_size: 1
    ref_dir: "data/ref"
    results_dir: "data/outputs/poses"

  

# System settings
system:
  device: "cuda"  # Options: cuda, cpu
  dtype: "bfloat16"  # Options: float16, float32, bfloat16
  seed: 42

# Paths

# Service settings
service:
  # max_query_size: "10MB"  # Maximum query image size
  supported_formats: ["jpg", "jpeg", "png"]
  temp_dir: "data/query"
  temp_rgb_name: "query.jpg"
  temp_depth_name: "query.npy"
  # cleanup_temp_files: true  # Clean up temporary files after processing

