# VPS Default Configuration

# Visual Place Recognition (VPR) settings
vpr:
  method: "megaloc"  # Options: netvlad, megaloc
  top_k: 3  # Number of similar images to retrieve
  output_dir: "data/outputs/"
  ref_data_path: "data/ref"
  ref_descriptors_path: "data/outputs/ref.h5"
  query_descriptors_path: "data/outputs/query.h5"
  pairs_file_path: "data/outputs/pairs.txt"
  use_spatial_filtering: False
  spatial_radius: 1.0
  similarity_threshold: 0.0001
  history_file: "data/outputs/last_pose.txt"
  

# Pose Estimation settings
pose:
  method: "vggt"  # Options: vggt, mast3r
  use_depth_pre: True
  depth_pre_model_path: "checkpoints/moge2_model.pt"
  vggt:
    model_path: "checkpoints/vggt_model.pt"  # If null, will download from HuggingFace
    image_size: 1024  # Input image size for VGGT
    ref_dir: "data/ref"
    results_dir: "data/outputs/poses"
  mast3r:
    model_path: "checkpoints/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth"
    image_size: 512  # Input image size for MASt3R
    batch_size: 1
    ref_dir: "data/ref"
    results_dir: "data/outputs/poses_mast3r"

  

# System settings
system:
  device: "cuda"  # Options: cuda, cpu
  dtype: "bfloat16"  # Options: float16, float32, bfloat16
  seed: 42

# Paths

# Service settings
service:
  # max_query_size: "10MB"  # Maximum query image size
  supported_formats: ["jpg", "jpeg", "png"]
  temp_dir: "data/query"
  temp_rgb_name: "query.jpg"
  temp_depth_name: "query.npy"
  # cleanup_temp_files: true  # Clean up temporary files after processing

# # Visualization settings
# visualization:
#   enabled: true
#   save_results: true
#   plot_matches: true 